### ISSUE TITLE
Connection setup

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#1]
## Summary

1. **As a** Integration Designer
1. **I want** to connect to my Applaud instance
1. **so that** I can use this in recipes

## Acceptance Criteria

1. I can see Applaud in the list of applications
1. My customers can see Applaud in the list of applications
1. I see it's called Applaud and uses a black background with white text
1. I can setup a new connection by setting the Tenant URL and API key
1. I can save my connection and see that the test validates that the connection works
1. If I add in a https:// prefix to the URL I see that this doesn't result in a double https://https:// URL that doesn't work
1. If I add in a http:// prefix to the URL I see that this is automatically converted to https when testing
1. If I don't add in a http(s) prefix I see that https:// is added automatically when testing
1. I see a sensible error message when the API key is invalid
1. I see a sensible error message when a valid API key is used but for a different tenant
1. I see a sensible error message when the domain doesn't exist
1. I see a sensible error message when the domain exists but is nothing to do with Applaud
1. I can use a custom domain when my tenant is configured to do so

### Connection setup
![Connection setup.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/90349a13-134b-456c-8e0b-e1d3c617ac4c)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by ssarap** [comment]
@duncancasemore To form the proper URL by stripping out http,https, is this expected to be written using ruby methods as currently Workato doesn't handle this.

**Comment by duncancasemore** [comment]
@ssarap yes that's what I was thinking.  If we can't do it easily it's not a problem - I imagine the connection test will simply fail...

**Comment by ssarap** [comment]
> @ssarap yes that's what I was thinking. If we can't do it easily it's not a problem - I imagine the connection test will simply fail...

yes

**Comment by vinaykumarkasireddy** [comment]
Established the connection to dev-workato tenant and the connection is successful. I can see the Applaud app in select apps.
![image](https://user-images.githubusercontent.com/20200783/95312398-81cc9e80-08ac-11eb-9306-8794fec341af.png)

**Comment by vinaykumarkasireddy** [comment]
## Acceptance Criteria

1. [x] I can see Applaud in the list of applications
1. [x] My customers can see Applaud in the list of applications
1. [x] I see it's called Applaud and uses a black background with white text
1. [x] I can setup a new connection by setting the Tenant URL and API key
1. [x] I can save my connection and see that the test validates that the connection works
1. [x] If I add in a https:// prefix to the URL I see that this doesn't result in a double https://https:// URL that doesn't work
1. [x] If I add in a http:// prefix to the URL I see that this is automatically converted to https when testing
1. [x] If I don't add in a http(s) prefix I see that https:// is added automatically when testing
1. [x] I see a sensible error message when the API key is invalid
1. [x] I see a sensible error message when a valid API key is used but for a different tenant
1. [x] I see a sensible error message when the domain doesn't exist
1. [x] I see a sensible error message when the domain exists but is nothing to do with Applaud
1. [x] I can use a custom domain when my tenant is configured to do so

For now, Using a single error message for all types of errors.
![image](https://user-images.githubusercontent.com/20200783/96236762-0e1c4700-0fba-11eb-9837-ceba9b12bdea.png)
Will change this later.
