### ISSUE TITLE
Update instance action

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#12]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that update data in Applaud
1. **so that** I can integrate actions from other apps back into Applaud

## Acceptance Criteria

1. I can select the Update instance action
1. I can select the model.  This has the same behavior as #11
1. When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
1. When I select the model, I then see all the model property fields similar to #11 except all fields are optional and collapsed by default (as it's a PATCH, any changes are merged in so no properties are required)
1. I see the Id field, which is the only one shown by default, is required, and of text type
1. I see that when this action fires it updates the data in Applaud by using the PATCH action
1. I see that all model properties (including the id) are available to use in later recipe actions as datapills
1. I see that the last updated by data in Applaud clearly shows it's been updated by the API
1. I see that the last updated by date in Applaud reflects the correct date/time stamp
1. I see that the created date is unchanged

### Update action
![Applaud action update.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/07778b8c-8d12-4f26-99bd-13dff1258e85)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
### Progress Update
- Created **update instance action** as per Wireframe
- need to to test this action.
Records are not fetched fetched from elastic. So unable to test.
A git is already raised in cloud repo to track this 
https://github.com/ApplaudSolutions/applaud-cloud/issues/3059

**Comment by GangamRitesh** [comment]
- [x] I can select the Update instance action
![image](https://user-images.githubusercontent.com/40355220/100221945-64789000-2f3f-11eb-8670-d485ea02166f.png)

- [x] I can select the model. 
![image](https://user-images.githubusercontent.com/40355220/100222112-a0abf080-2f3f-11eb-90f2-6b2b9cc6e87d.png)

- [x] When I select the model, I then see all the model property fields similar to #11 except all fields are optional and collapsed by default (as it's a PATCH, any changes are merged in so no properties are required)

- [x] I see the Id field, which is the only one shown by default, is required, and of text type
![image](https://user-images.githubusercontent.com/40355220/100222444-16b05780-2f40-11eb-908d-0bcd935f4c32.png)

- [x] I see that when this action fires it updates the data in Applaud by using the PATCH action
- [x] I see that all model properties (including the id) are available to use in later recipe actions as datapills
![image](https://user-images.githubusercontent.com/40355220/100222547-419aab80-2f40-11eb-8f13-b3ab501ae6ec.png)

- [x] I see that the last updated by date in Applaud reflects the correct date/time stamp
- [x] I see that the created date is unchanged
![image](https://user-images.githubusercontent.com/40355220/100223265-42800d00-2f41-11eb-83b5-d6fd8abfb075.png)

### Pending items
- [ ] When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
![image](https://user-images.githubusercontent.com/40355220/100222279-df41ab00-2f3f-11eb-972e-b59d7f343efa.png)
Checked with workato team on this there is no function to get singular of given model name
- [ ] I see that the last updated by data in Applaud clearly shows it's been updated by the API

- As of now last updated by is stored as Anon, there is a cloud git to track this
![image](https://user-images.githubusercontent.com/40355220/99961774-015af200-2db5-11eb-8793-cfc6765ad4d8.png)

https://github.com/ApplaudSolutions/applaud-cloud/issues/2710

Note:
In the connector initially there is a validation to check if record to be updated is already present in model. But there is an bug in cloud , get request made to elastic is not working as expected
https://github.com/ApplaudSolutions/applaud-cloud/issues/2980

**Comment by ssarap** [comment]
@GangamRitesh I think Last update by is now fixed?

**Comment by GangamRitesh** [comment]
Yes @ssarap its fixed now
