### ISSUE TITLE
Delete instance action

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#14]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that delete data in Applaud
1. **so that** I can integrate actions from other apps back into Applaud

## Acceptance Criteria

1. I can select the Delete instance action
1. I can select the model.  This has the same behavior as #11
1. When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
1. When I select the model, I only see Id field, which is required, and of text type
1. I see that when this action fires it deletes the data in Applaud by using the DELETE action
1. I can use a result status as a datapill in later recipe actions to branch based on whether the delete was successful or not

### Delete action
![Applaud action delete.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/a0393bac-148e-4b1f-835b-44a033e16653)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
- [x] I can select the Delete instance action
![image](https://user-images.githubusercontent.com/40355220/100321843-5717e000-2fe9-11eb-94aa-561f3c3bcc75.png)

- [x] I can select the model.
![image](https://user-images.githubusercontent.com/40355220/100321911-70209100-2fe9-11eb-9de8-bf549cd77053.png)

- [x] When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
![image](https://user-images.githubusercontent.com/40355220/100322010-9f370280-2fe9-11eb-814e-0923ecc6d8e9.png)

- [x] When I select the model, I only see Id field, which is required, and of text type
![image](https://user-images.githubusercontent.com/40355220/100322030-a5c57a00-2fe9-11eb-8728-7e3ac63cae37.png)

- [x] I see that when this action fires it deletes the data in Applaud by using the DELETE action
- [x] I can use a result status as a datapill in later recipe actions to branch based on whether the delete was successful or not
Status is set to "success" or "failed" based on delete operation
![image](https://user-images.githubusercontent.com/40355220/100322097-c2fa4880-2fe9-11eb-9c7b-b1f14f288242.png)
