### ISSUE TITLE
Search instances action

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#15]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that search data in Applaud
1. **so that** I can use the results and perform follow-up actions in Applaud or other applications

## Acceptance Criteria

1. I can select the Search instances action
1. I can select the model.  This has the same behavior as #11
1. When I select the model, I see this shows in lower case PLURAL in the action title above and in the recipe viewer
1. When I select the model, I then see all the model property fields as optional and collapsed by default
1. I see the fields in the order specified by the Applaud property order (not alphabetical)
1. I see the Id field, which is the first one shown
1. I see that I can specify the max results.  Where not specified, this defaults to 10
1. I cannot specify a maximum that is greater than 200
1. If the Applaud API returns a paginated set of results that I do not neglect subsequent pages up to the maximum results.  For example, if the Applaud API page is 10 and my maximum is 50, I will need to iterate over 5 pages of results (probably easier to set the maximum as the API page size if possible)
1. I can specify the sort properties together with ascending or descending
1. I can specify multiple sort properties.  These are all sorted by either ascending or all sorted by either descending (I cannot have 1 ascending and another descending)
1. I can select free-text properties in the sort list and these work as expected
1. I can select number properties in the sort list and these work as expected
1. I can select boolean properties in the sort list and these work as expected
1. I can select date properties in the sort list and these work as expected
1. I can select date/time properties in the sort list and these work as expected
1. I can select file properties in the sort list and these work as expected (sorted by file id)
1. I can select user properties in the sort list and these work as expected (sorted by user id)
1. I can select email properties in the sort list and these work as expected
1. I can select URL properties in the sort list and these work as expected
1. I can select lookup properties in the sort list and these work as expected (sorted by lookup id)
1. I can select foreign key properties in the sort list and these work as expected (sorted by foreign key id)
1. I can select icon properties in the sort list and these work as expected
1. I can select color properties in the sort list and these work as expected
1. I cannot select date range or geopoint properties in the sort list
1. I see that when this action fires it searches the data in Applaud (GET) by using the given criteria
1. I do not have to enter any search criteria; this simply retrieves all instances up to the max results
1. I see that the search results are available as a list datapill in later actions, with detail pills for each property of the item
1. I see that I can use the search results count as a datapill

### Search action
![Applaud action search.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/98aff01e-c883-4b84-8c27-5634d8b91e53)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
- [x] I can select the Search instances action
![image](https://user-images.githubusercontent.com/40355220/104722676-2f750680-5754-11eb-8f14-0c6282afb924.png)

- [x] When I select the model, I see this shows in lower case PLURAL in the action title above and in the recipe viewer

![image](https://user-images.githubusercontent.com/40355220/104722695-3c91f580-5754-11eb-9a87-9646be84f8d8.png)

 - [x] When I select the model, I then see all the model property fields as optional and collapsed by default
![image](https://user-images.githubusercontent.com/40355220/104722766-58959700-5754-11eb-83f5-d23edd3440c4.png)

- [x]  I see the fields in the order specified by the Applaud property order (not alphabetical)
![image](https://user-images.githubusercontent.com/40355220/104722815-664b1c80-5754-11eb-82a0-b20b8a522657.png)

- [x]  I see that I can specify the max results.  Where not specified, this defaults to 10
- [x]  I cannot specify a maximum that is greater than 200
![image](https://user-images.githubusercontent.com/40355220/104722884-77942900-5754-11eb-807d-8bb63df9cdc0.png)


- [x]  If the Applaud API returns a paginated set of results that I do not neglect subsequent pages up to the maximum results.  For example, if the Applaud API page is 10 and my maximum is 50, I will need to iterate over 5 pages of results (probably easier to set the maximum as the API page size if possible)
- [x]  I can specify the sort properties together with ascending or descending
![image](https://user-images.githubusercontent.com/40355220/104722962-8aa6f900-5754-11eb-90c6-01d7712e299b.png)
![image](https://user-images.githubusercontent.com/40355220/104722981-92669d80-5754-11eb-8407-794e4d7b2d5d.png)


- [x]  I can specify multiple sort properties.  These are all sorted by either ascending or all sorted by either descending (I cannot have 1 ascending and another descending)
![image](https://user-images.githubusercontent.com/40355220/104723113-c346d280-5754-11eb-965a-e0fe2ee72403.png)


- [x]  I can select free-text properties in the sort list and these work as expected
- [x]  I can select number properties in the sort list and these work as expected
- [x] I can select boolean properties in the sort list and these work as expected
- [x] I can select date properties in the sort list and these work as expected
- [x] I can select date/time properties in the sort list and these work as expected
- [x] I can select file properties in the sort list and these work as expected (sorted by file id)
- [x] I can select user properties in the sort list and these work as expected (sorted by user id)
- [x] I can select email properties in the sort list and these work as expected
- [x] I can select URL properties in the sort list and these work as expected
- [x] I can select lookup properties in the sort list and these work as expected (sorted by lookup id)
- [x] I can select foreign key properties in the sort list and these work as expected (sorted by foreign key id)
- [x] I can select icon properties in the sort list and these work as expected
- [x] I cannot select date range or geopoint properties in the sort list
- [x] I see that when this action fires it searches the data in Applaud (GET) by using the given criteria
- [x] I do not have to enter any search criteria; this simply retrieves all instances up to the max results
- [x] I see that the search results are available as a list datapill in later actions, with detail pills for each property of the item
![image](https://user-images.githubusercontent.com/40355220/104723619-88916a00-5755-11eb-993d-933352f4f3f1.png)
- [x] I see that I can use the search results count as a datapill
![image](https://user-images.githubusercontent.com/40355220/104723675-a1018480-5755-11eb-9dbf-64e3038e546e.png)
** Here the value of count is the number of records fetched, not the number of records present in the model.

### Notes
- [ ] I can select the model. This has the same behavior as #11
Unlike other actions, in search instance action user model can also be selected.
**Search instance action is configured in Applaud Connector2**

**Comment by GangamRitesh** [comment]
As a part of the Search action as per AC 25, other than **date-time range** fields and **geo point** fields, all other fields can be used for search and sort instances. 
Now that lookups are configured, search action should also fetch records filtered/sorted by lookup values. But in the lookup if  
   **allow multiple** is set to true, search action is not fetching results(getting error response from cloud).
![image](https://user-images.githubusercontent.com/40355220/105178987-c116b680-5b4e-11eb-9e16-e29ef60e7fad.png)
https://dev-workato-com.applaudhcm.com/api/custom/tests?filter[where][statusId]=6006a82c589667801c2d6e79&filter[where][employeeTypeIds][inq]=6007d80f01a9448a0c26171e&filter[where][employeeTypeIds][inq]=6007d80f01a9448a0c26171f
On trying the same using filter {"getFrom":"mongo"} Cloud is returning the results.
So there are 2 Options 
1. Raise a git in the cloud board to fetch results for the lookup fields having multiple values.
2. Disable lookup fields in search and sort actions in workato.
@duncancasemore  can you please review.

**Comment by duncancasemore** [comment]
@GangamRitesh can we include lookup properties on search when allow multiple is unticked but hide it when it's ticked?

**Comment by GangamRitesh** [comment]
Yes @duncancasemore 
It is possible

**Comment by ssarap** [comment]
@GangamRitesh Do we have tracking git for lookups filter not working when multiple values are allowed?
