### ISSUE TITLE
Autocomplete values in actions for lookup model properties

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#19]
## Summary

1. **As a** Integration Designer
1. **I want** to see autocomplete values when entering a field based on a "Lookup" model property
1. **so that** it's easier for me to pick fixed values at design time when I don't need to use datapills

## Acceptance Criteria

1. I can see a list of autocomplete values when entering a field based on a "Lookup" model property
1. I see the list of values presented in the sequence order in Applaud (not alphabetical)
1. When the action runs I see that the lookup id is loaded in, not the display value
1. When I edit a previous action that sets a lookup, I see it shows the display value, even though the id is used behind-the-scenes

## Wireframes and mockups

Not required

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
Update lookup field so that lookup value id can also be passed to lookup field.
![image](https://user-images.githubusercontent.com/40355220/108957991-5c440400-7698-11eb-9352-f0946f565fe3.png)
![image](https://user-images.githubusercontent.com/40355220/108958089-7978d280-7698-11eb-92b8-8cc858baec24.png)
