### ISSUE TITLE
Option to set 'owner' model property in actions

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#23]
## Summary

1. **As a** Integration Designer
1. **I want** to set the owner model property in various actions
1. **so that** I don't have to build additional workflows in Applaud just to set this value

## Acceptance Criteria

1. I see the 'Owner' field in all actions
1. It's always optional, so collapsed by default
1. I see the field below id but above other optional properties
1. I see it in batch operations when mapping properties for each list source item
1. I see that it's of 'user' type, so will work with #21 when that's built
1. I see that when it's set, it uploads correctly into Applaud

### Owner field
![Screenshot 2020-10-02 at 15.09.33.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/183a74a0-9981-4219-a1ad-f36197753f63)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by vinaykumarkasireddy** [comment]
Workato automatically setting the owner to the logged in user by default. So, closing this.
