### ISSUE TITLE
Ability to use 'User' model in update, and search actions

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#24]
## Summary

1. **As a** Integration Designer
1. **I want** to define recipe actions that update and search Applaud users
1. **so that** I can automate user provisioning and changes

## Acceptance Criteria

1. <s>I can select the User model in the Create instance action</s>
1. I can select the User model in the Update instance action
1. I can select the User model in the Upsert instance action
1. I can select the User model in the Search instances action
1. <s>I can select the User model in the Create instances in batches action</s>
1. I can select the User model in the Update instances in batches action
1. I can select the User model in the Upsert instances in batches action
1. I do not see the User model in the Delete action
1. When I select the User model, I see all of the properties, including custom user properties.  Today, this includes email, name, initials, avatar, send email invitation or not + custom properties
1. For create and upsert actions, I see that the properties are required or not dependent on the Applaud property settings
1. If I'm using an update or upsert action, I see the Id field is the first one
1. If I'm updating, I see the Id field is required (it's optional for upserting)
1. For update actions, I see all properties are optional except for Id
1. I note that the users save correctly for all create and update actions
1. I note that I can search for users and use the output for subsequent recipes

### Create instance action with user model selected
![Applaud action create user.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/bc3749b8-3d3b-4e31-85f2-179fe556da68)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by ssarap** [comment]
@vinaykumarkasireddy Currently we are able to select User model in all the actions. So what is this GIT about?

**Comment by vinaykumarkasireddy** [comment]
@ssarap Initially, 'User' model was restricted in all the actions. It is not restricted any more. We can close this.
