### ISSUE TITLE
Upload file action

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#25]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that upload files to Applaud
1. **so that** I can integrate files from other apps back into Applaud

## Acceptance Criteria

1. I can select the Upload file action
1. I can enter the source URL of the file I wish to upload, that this field is required and that it's of URL type
1. When I use this action I see that this file uploads into Applaud
1. I see that I can use the uploaded file's properties as datapills in later actions.  Specifically, I can use File Id, URL, Filename and Mime Type
1. If the file upload fails (eg, too big, blacklisted extension, has a virus, etc), I see the recipe errors (unless wrapped in a try catch)

### Upload file action
![Applaud action upload a file.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/c1a2f27b-c105-4a09-ad8f-4ca36b5ba139)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by vinaykumarkasireddy** [comment]
@lewie6 Could you share the apis used to upload and download a file in applaud cloud. Please provide if there is any documentation on this. Thanks.

**Comment by hgajula-applaud** [comment]
@vinaykumarkasireddy see this https://support.applaudsolutions.com/hc/en-us/articles/360009358278-Imports-and-Exports
You can find out the API by looking at the network trace when trying the above notes.. 
If this does not help, then wait for @lewie6 or @ApplaudSolutions/cloud-team help.

**Comment by vinaykumarkasireddy** [comment]
Sure @hgajula-applaud Thank you.

**Comment by vinaykumarkasireddy** [comment]
Getting the below error while uploading a document to applaud cloud.

Exception in Vinay_Connector. 404 Not Found: {"error":401,"data":{"messages":[{"mood":"assertive","timeout":15000,"text":"Unable to import file","body":null,"stack":"Error: null\n at Object.handler (/home/mgtmp/workspace/applaud-cloud/server/config.local.js:19:17)\n at restErrorHandler (/home/mgtmp/workspace/applaud-cloud/node_modules/strong-remoting/lib/rest-adapter.js:391:17)\n at Layer.handle_error (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/layer.js:71:5)\n at trim_prefix (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:315:13)\n at /home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:284:7\n at Function.process_params (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:335:12)\n at next (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:275:10)\n at Layer.handle_error (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/layer.js:67:12)\n at trim_prefix (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:315:13)\n at /home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:284:7\n at Function.process_params (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:335:12)\n at Immediate.next (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:275:10)\n at Immediate._onImmediate (/home/mgtmp/workspace/applaud-cloud/node_modules/express/lib/router/index.js:635:15)\n at runCallback (timers.js:706:11)\n at tryOnImmediate (timers.js:676:5)\n at processImmediate (timers.js:658:5)\n at process.topLevelDomainCallback (domain.js:126:23)"}]}}.

@duncancasemore/ @lewie6 Can you help why this error shows up. Do i need to set anything?
Used content_type as "multipart/form-data; boundary=#{boundary}"
set the boundary to below
'Content-Disposition: form-data; name="file"; filename="Milestone Patch Build Steps.docx"
Content-Type: image/png'

**Comment by ssarap** [comment]
@lewie6 @curioustushar Could you pls provide an update on this.

**Comment by ssarap** [comment]
To review the same with Workato.

**Comment by vinaykumarkasireddy** [comment]
Need to input the content type also here, Applaud cloud api is expecting the content-type.
After passing the correct content type, file is uploaded into applaud cloud.

Input fields for the action:
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/91bc8f0f-6392-446b-a92d-465c181c1bc7)

Output Fields:
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/63e647ff-ded5-4df9-999d-3e8eaa7d8260)

@duncancasemore Please review.
