### ISSUE TITLE
New/Update instances in batch triggers are not fetching data in workato recipes. 

### ISSUE THREAD

**Issue by GangamRitesh** [ApplaudSolutions/Applaud-Workato-Connector#28]
**Describe the bug**
New/Update instance triggers are not fetching data in workato recipes 

**Steps to reproduce**
1. Navigate to workato recipes with New/Update instances in batch triggers
1. Test the recipe
1. See that no records are picked even there are new/updated records.

**Expected behavior**
New/updated records should be fetched by the trigger in recipes.

**Additional context**
Triggers were working fine in sdkconnectors. Workato team is checking on this

**Comment by ssarap** [comment]
This is being reviewed by Chandra from Workato.
Please note that I have given him access to the Connector.

**Comment by GangamRitesh** [comment]
> I have given him access to the Connector.

@ssarap , Updated Chandra on this

**Comment by GangamRitesh** [comment]
Closing this as data is now fetched from New/Update instances in batch triggers

**Comment by ssarap** [comment]
@GangamRitesh Is this achieved through changes in SDK connector, if yes are the changes present in the latest released connector?

**Comment by GangamRitesh** [comment]
Yes @ssarap , Changes are already present in the latest version of SDK
