### ISSUE TITLE
Create a user action

### ISSUE THREAD

**Issue by karthmoh** [ApplaudSolutions/Applaud-Workato-Connector#31]
## Summary

1. **As a** Integrations designer
1. **I want** to define recipe actions that would create users
1. **so that** I can automate the user provisioning

## Acceptance Criteria
1. In 'Create an instance' real-time action, I can pick the 'User' model
1. I cannot pick the User model in the delete or bulk actions.  Update/upsert - QUESTION see notes.
1. When I pick the User model, I see some special fields for Email (required), Name (required), Initials (required), Avatar (optional), Roles (optional, multi-select), Send email invitation (required; defaults to No); and then any custom user properties
1. When I set these the user is created in the same way as using the Invite form
1. Notably if I send 'Send email invitation' as No the user doesn't get an email (dependent on https://github.com/ApplaudSolutions/applaud-cloud/issues/3779)

### Create a model action with User selected
![Applaud action create user](https://user-images.githubusercontent.com/7467052/115539186-91ce2d80-a294-11eb-9935-dc59de0bd94c.png)

## Notes

* Should we also have stories to allow a user update in Update an action as well?
* What about upserting based on email address -- too complicated?
 
## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by duncancasemore** [comment]
@karthmoh I've regroomed this.

**Comment by GangamRitesh** [comment]
Hi @duncancasemore ,
There is no option to create a record in User with APIs
![image](https://user-images.githubusercontent.com/40355220/115708583-d093de80-a38d-11eb-8de9-db119fa168ab.png)
We need to create a new action **Invite a user to ApplaudHR** which sends a mail to invite the User.

**Comment by GangamRitesh** [comment]
Tried to use APIs **/api/users/invite** to invite users, **/api/role-grants** to fetch all the roles in tenant. But API keys don't have access to call these APIs. Without access to these APIs we are blocked here.

**Comment by duncancasemore** [comment]
@GangamRitesh see here for API:
https://github.com/ApplaudSolutions/applaud-cloud/issues/3779

I guess this action will need to have 2 internal API calls: 1 API call to invite and then a second to PATCH the custom user.  Not sure about roles...

**Comment by GangamRitesh** [comment]
@duncancasemore , @lewie6 
As a part of git https://github.com/ApplaudSolutions/applaud-cloud/issues/3779, role grants are added to the Users model so we have access to **/api/users/invite**. 
Currently, we don't have access to  **/api/role-grants**. Can we include this as a part of git https://github.com/ApplaudSolutions/applaud-cloud/issues/3779 or create a new git for this.
> then a second to PATCH the custom user.

When an invite is sent to the user, a user record is created in both seeded as well as custom user models. Do we need patch request?

**Comment by duncancasemore** [comment]
@GangamRitesh why don't we leave roles out of this story for now then.  I think roles can be assigned automatically using workflow in Applaud, which is probably a better solution anyway.

I figured you'd need a PATCH on custom user to update it with the custom fields (eg, personId, countryOfWork, whatever).  If you can do that in the initial invite, fine.

**Comment by GangamRitesh** [comment]
> @GangamRitesh why don't we leave roles out of this story for now then. I think roles can be assigned automatically using workflow in Applaud, which is probably a better solution anyway.

Sure @duncancasemore. Roles are assigned in worflow.


> I figured you'd need a PATCH on custom user to update it with the custom fields (eg, personId, countryOfWork, whatever). If you can do that in the initial invite, fine.

- Similar to roles, custom user details (personId, countryOfWork, phoneNumber) are updated as part of workflows.
![image](https://user-images.githubusercontent.com/40355220/116071116-15c85100-a6ab-11eb-8bed-c96c3f106ebe.png)
 Can we avoid this one for now as well?

- As the API calls we are making in **create instance action** ( **_/api/custom/model_** ) is different to calls we are making to **invite user** ( **_/verifyEmail/email_** , **_/api/users/invite_** ), shall we create a new action for this?

**Comment by duncancasemore** [comment]
@GangamRitesh happy to break it out.  Do we use 'Create an instance' action and pick a special 'User' option to invite (with special fields) or build something custom?  I think it would be neater to use the same action, then we can use 'Update an instance' action for patching a user and 'Delete an instance' to grant a user the deleted role.  We'd have to think about bulk as well...

**Comment by GangamRitesh** [comment]
Sure @duncancasemore , will try to include in the create instance action.

**Comment by GangamRitesh** [comment]
@duncancasemore , Build create user instance action.
Steps involved in create user action :
1. Verify the email
2. Invite user
3. Search for user in custom user with input email.
4. Update custom user record with standard(input) properties.
#### Issues found in create user instance action
1. After inviting the user, sometimes unable to find the user in the custom user model due to elastic mongo sync issues.
2. After inviting the user, as there are workflows on the user model there is a possibility of getting an error on trying to update the custom user record(step 4) as record might be in pending state ( isInWorkflow = true),
3. Cannot set the properties in the user model as Required to True. As properties in the user model are not set to required.
![image](https://user-images.githubusercontent.com/40355220/116564656-ce4bfa00-a922-11eb-972f-561405c2415c.png)
Able to set all the standard properties as required or all the properties as optional. (cannot set Email (required), Name (required), Initials (required), Avatar (optional))
4. Cannot set these standard properties in the order shown in schema page (Order of properties is set in the order returned by cloud).
![image](https://user-images.githubusercontent.com/40355220/116568027-c772b680-a925-11eb-82ef-7a47f2c74ae8.png)
![image](https://user-images.githubusercontent.com/40355220/116568143-de190d80-a925-11eb-930c-d33e3082ac2c.png)
![image](https://user-images.githubusercontent.com/40355220/116568248-f38e3780-a925-11eb-8863-afb6265e5f21.png)

**Comment by GangamRitesh** [comment]
Raised issues in cloud board.
https://github.com/applaudsolutions/applaud-cloud/issues/3844
https://github.com/ApplaudSolutions/applaud-cloud/issues/3875

**Comment by ssarap** [comment]
This has been handled as part of Create instance action.
Now we can choose User model and fill the details to send create and invite.
