### ISSUE TITLE
Delete instance action not working

### ISSUE THREAD

**Issue by vinaykumarkasireddy** [ApplaudSolutions/Applaud-Workato-Connector#34]
**Describe the bug**
Delete instance action is not working as expected.

**Steps to reproduce**
1. Configure a recipe
1. Use delete action to delete a particular record
1. See the response as success, but when queried in the model, the record still appearing.

**Expected behavior**
The deleted record should not appear in the model.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/60016264-9902-4b99-8d2b-cab6d386db80)
**URL**

**Additional context**

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
Fixed issue with delete action.
There is an issue with the SDK connector due to which cloud API is not called.
