### ISSUE TITLE
New/updated instances batch trigger

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#4]
## Summary

1. **As a** Integrations Designer
1. **I want** to create recipes that periodically trigger from new or updated Applaud instances
1. **so that** I can integrate actions performed in Applaud with other applications

## Acceptance Criteria

1. I can select a 'New/updated instances' batch trigger for the Applaud app
1. I see that this trigger is labeled Batch
1. I can set the model, first started date, trigger interval, poll, and trigger conditions.  These have identical behavior to #2.
1. In subsequent actions in the recipe, I can see the list of items and all their model properties as datapills.  I see that each Applaud property type is typed correctly in its datapill.
1. When this recipe first runs, I see that it picks up all created or updated records from the initial recipe date (using `updated` property in Applaud)
1. When this recipe next runs, I see that it picks up all created or updated records from the last run date (using `updated` property in Applaud)
1. If the trigger returns more instances than the batch size, I see it processes them in batches
1. If the Applaud API returns just one page of results, I see that the connector handles paginating through all results not just the first page (`filter={"offset":10,"limit":2}`)
1. I see that the trigger runs as per the specified interval

### New/updated real-time trigger

_Note: this wireframe is for a slightly different trigger, so there will be minor (obvious) variations_

![Applaud trigger setup](https://user-images.githubusercontent.com/7467052/94832532-ecda2900-0405-11eb-8231-706941f4c777.png)

## Open Issues

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by vinaykumarkasireddy** [comment]
1. [x] I can select a 'New/updated instances' batch trigger for the Applaud app
1. [] I see that this trigger is labeled Batch
1. [x] I can set the model, first started date, trigger interval, poll, and trigger conditions.  These have identical behavior to #2.
1. [x] In subsequent actions in the recipe, I can see the list of items and all their model properties as datapills.  I see that each Applaud property type is typed correctly in its datapill.
1. [x] When this recipe first runs, I see that it picks up all created or updated records from the initial recipe date (using `updated` property in Applaud)
1. [] When this recipe next runs, I see that it picks up all created or updated records from the last run date (using `updated` property in Applaud)
1. [x] If the trigger returns more instances than the batch size, I see it processes them in batches
1. [x] If the Applaud API returns just one page of results, I see that the connector handles paginating through all results not just the first page (`filter={"offset":10,"limit":2}`)
1. [x] I see that the trigger runs as per the specified interval
