### ISSUE TITLE
Custom action in Applaud connector

### ISSUE THREAD

**Issue by Ritesh717** [ApplaudSolutions/Applaud-Workato-Connector#40]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that make custom requests in Applaud
1. **so that**  I can make custom calls to applaud and doesn't require SDK changes. Replica of HTTP request with Applaud connection

## Acceptance Criteria

-

### [Title of wireframe/mockup 1]
[Image of wireframe/mockup 1]

### [Title of wireframe/mockup 2]
[Image of wireframe/mockup 2]

## Notes

* > Here goes a quote from an email
* Here goes any other useful information…

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by duncancasemore** [comment]
@Ritesh717 please can you share some example requirements here? Would be good to rewrite the story around requirements rather than the solution.

**Comment by Ritesh717** [comment]
@duncancasemore,

Custom action is implemented in almost all the other SDK connectors.

Few use cases of this custom action in Applaud.

1. In a case where the developer needs to call other APIs available on the model-api's page.
![image](https://user-images.githubusercontent.com/40355220/147054564-6a984a79-338d-460b-9686-77f1b2a70bf5.png)

2. Developer requires related model data in a search instance action output.
Eg :
 > 
    {
            "eventTypeId": "5e5cb199a190e93a0b3ba2e6",
            "name": "test",
            "startAndEnd": {
                "startDate": "03/03/2020 12:00 AM",
                "endDate": "03/05/2020 12:00 AM"
            },
            "link": "",
            "eventDetail": "test",
            "backgroundColor": "",
            "textColor": "",
            "statusBarColor": "",
            "secondaryIcon": "",
            "fileId": "",
            "statusId": "5f11925cd86395580f47b114",
            "created": "12/14/2021 11:58 AM",
            "updated": "12/14/2021 11:58 AM",
            "id": "61b839a0dcd6789205f39394",
            "lastUpdatedById": "API key 1",
            "event-type": {
                "label": "Vacation or holiday",
                "isDeleted": false,
                "propertyId": "5e5cb195a190e93a0b3ba2e1",
                "modelName": "LookupOption",
                "created": "03/02/2020 12:41 PM",
                "updated": "06/02/2021 5:58 PM",
                "id": "5e5cb199a190e93a0b3ba2e6",
                "tenantId": "5e5765521116196d39b5eebf",
                "ownerId": "5defaa81ed49e41148a7d16e",
                "lastUpdatedById": "5defaa81ed49e41148a7d16e"
            },
            "status": {
                "label": "Pending",
                "isDeleted": false,
                "propertyId": "5f119254d86395580f47b10f",
                "modelName": "LookupOption",
                "created": "07/17/2020 5:28 PM",
                "updated": "07/17/2020 5:28 PM",
                "id": "5f11925cd86395580f47b114",
                "tenantId": "5e5765521116196d39b5eebf",
                "ownerId": "5defaa81ed49e41148a7d16e"
            },
            "modelName": "5e5765521116196d39b5eebf-CalendarEvent"
    } 
3. In a case where the developer needs a search operation that includes multiple **and, or** filters 

#### Custom action implementation in other SDK connectors
![image](https://user-images.githubusercontent.com/40355220/147055231-8771c69d-1bdc-4d9c-9f22-f51ca7d1522d.png)
![image](https://user-images.githubusercontent.com/40355220/147055358-a055f102-4c5f-4b5f-a711-3ee6c798e6d9.png)
![image](https://user-images.githubusercontent.com/40355220/147055023-5a47ebf9-53ab-4b9d-afcc-239151c8fea2.png)
![image](https://user-images.githubusercontent.com/40355220/147055096-a0054d2b-2474-408b-9d87-bfe9081971b7.png)

**Comment by duncancasemore** [comment]
@Ritesh717 it's true, many other connectors do have this.  It looks to me like an easy alternative to building out the connector properly :-).  To be fair, some have thousands of end-points and have built actions for a couple of common use-cases but then use a custom action as a 'catch all' for everything else.

I'd like us to first explore enhancing the connector before we do this, as custom actions are closer to custom code, may use unpublished API features and liable to break recipes with future changes.  As an alternative, for example, when I first wireframed the search action in the connector I had put in 'Related models':

![Applaud action search](https://user-images.githubusercontent.com/7467052/147072308-eec7ed25-d2c0-432d-b3e1-4e8e597d6487.png)

I think this would be really useful.  I hear you on the and/or filters (I think we can only do 'and' today).  Would be good to hear some real life use-cases around that to see if it's worth us enhancing the search action further?

**Comment by Ritesh717** [comment]
Sure @duncancasemore ,
Will try to include related model data into the search instance action without breaking current recipes.
There are few cases for customers where search action requires **greater than, less than** conditions for filters(for date, number). We can try to include these features in search action but will result in breaking the working recipes.
 
We can achieve this requirement by this custom action or and create one more Advanced search action to include greater than, less than conditions and data from related models

**Comment by duncancasemore** [comment]
@Ritesh717 rather than having this general 'custom action' story, I suggest we raise separate stories for 'Include related models in search action', 'Greater than/less than searching on dates and numbers'.

**Comment by Ritesh717** [comment]
Sure @duncancasemore ,
Will raise separate stories for these.
