### ISSUE TITLE
Add 'fileHref' property to download file action output datapill

### ISSUE THREAD

**Issue by vinaykumarkasireddy** [ApplaudSolutions/Applaud-Workato-Connector#42]
## Summary

1. **As a** [Integration designer]
1. **I want** [to add 'fileHref' property to download file action output datapill]
1. **so that** [I can download the file from applaud]

## Acceptance Criteria

1. [I can see 'fileHref' property in the output datapill of download file action]

### [Title of wireframe/mockup 1]
[Image of wireframe/mockup 1]

### [Title of wireframe/mockup 2]
[Image of wireframe/mockup 2]

## Notes

* > Here goes a quote from an email
* Here goes any other useful information…

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive tests:**
- [ ] Should do something
- [ ] Should do something else

**Negative tests:**
- [ ] Should not error when the collective crazy behavior of 1 million users do something unexpected
- [ ] Should not error when the collective crazy behavior of 1 million users do something else unexpected
- [ ] Should not error when the collective crazy behavior of 1 million users do something else unexpected
- [ ] Should not error when the collective crazy behavior of 1 million users do something else unexpected
- [ ] Should not error when the collective crazy behavior of 1 million users do something else unexpected

**Comment by vinaykumarkasireddy** [comment]
![image](https://user-images.githubusercontent.com/20200783/151393716-a4f3f069-7ff9-443e-a71e-0d17902ab89b.png)
'fileHref' property has been added to the datapill.
@karthmoh Please verify.

**Comment by karthmoh** [comment]
Hi @vinaykumarkasireddy 

As discussed, I could not see this datapill in TA-EU. Could you please check.

Thanks,
Karthik.

**Comment by vinaykumarkasireddy** [comment]
@karthmoh It is working now on KCH tenant. Please verify now.
![image](https://user-images.githubusercontent.com/20200783/151532208-dbde443a-4db3-405b-acf8-5fe66f6c0665.png)

**Comment by karthmoh** [comment]
Thanks @vinaykumarkasireddy I am able to get the property in TA-EU as well.

**Comment by vinaykumarkasireddy** [comment]
Closing this issue as the 'fileHref' property added to download file action.
