### ISSUE TITLE
For lookup properties we need both id and value to come in data pill

### ISSUE THREAD

**Issue by kushalapplaud** [ApplaudSolutions/Applaud-Workato-Connector#43]
## Summary

1. **As a** integration expert
1. **I want** to create recipes where i require the value from the lookup table instead of just id
1. **so that** I don't need to maintain separate lookup in workato

## Acceptance Criteria

1. [If I do A, B should happen]
1. [If I do C, D should happen]

### [Title of wireframe/mockup 1]
[Image of wireframe/mockup 1]

### [Title of wireframe/mockup 2]
[Image of wireframe/mockup 2]

## Notes

* > Here goes a quote from an email
* Here goes any other useful information…

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by duncancasemore** [comment]
@ssarap we welcome your views on how this can be achieved and its complexity. From here we can prioritise accordingly.

**Comment by kushalapplaud** [comment]
Data pill how it comes now:-
![image](https://user-images.githubusercontent.com/45057962/160556812-59f5d887-8209-48d7-baea-d086d0a5b2c3.png)

When maintaining data in lookup in workato how the data pill comes:-
![image](https://user-images.githubusercontent.com/45057962/160556914-e7d605b3-5adf-4ad0-8274-01db59621c10.png)

Either we need similar data pill for lookups like we can expand and both value and id shows up, else we need data pill like pilon - id and pilon - value

**Comment by ssarap** [comment]
@duncancasemore This is a little similar to what we are trying to achieve in #41, we are currently blocked on this.
Will update you post discussion with the Workato team.

**Comment by duncancasemore** [comment]
@ssarap ok thanks

**Comment by vinaykumarkasireddy** [comment]
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/c42908ce-de1d-4b72-95c2-119d740dde2e)

![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/3dfa97c0-465e-46a0-880a-067614343d4f)

![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/15ee6b10-6efc-4623-8b5a-65e202b1be1d)

@kushalapplaud Is this you are expecting?

If user tries to enter value for both id and value with different values, it would be difficult what to enter. Or we can add a hint like 'Choose only one, either id or value'

**Comment by kushalapplaud** [comment]
@vinaykumarkasireddy - One doubt here we are selecting from list. We need the option to map it to the value that is retrieved from search action of the model. In search action for a lookup property both these values should show up in data pill.

**Comment by vinaykumarkasireddy** [comment]
Yes @kushalapplaud. U can see the current step output here. Id, value both are selectable here.
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/7bb013df-b503-490d-b271-2ef2013d0d2b)

**Comment by ssarap** [comment]
There is a limitation in Workato SDK to manipulate the meta data received from Cloud API. Discussed same with Chandra from Workato, they are reviewing it. Meanwhile working on a workaround to call cloud API which gets lookup properties of a model.

**Comment by vinaykumarkasireddy** [comment]
Raised a cloud git to expose the model properties api. [ApplaudSolutions/applaud-cloud/issues/5055](https://github.com/ApplaudSolutions/applaud-cloud/issues/5055)

**Comment by ssarap** [comment]
@vinaykumarkasireddy I made a few tweaks to the Connector SDK to pull lookup Id, Value(Label) for all the lookups.
Output data fields are now working as expected.
![image](https://user-images.githubusercontent.com/12637618/163925197-e2d6a025-f2c8-4ef9-a91a-1e0359a4fe8c.png)

@kushalapplaud If you would like to test it download the connector from here and use it.
https://app.workato.com/custom_adapters/33191/details?token=363f7bc0
@vinaykumarkasireddy Pls review the SDK changes and release it post your testing.

**Comment by vinaykumarkasireddy** [comment]
Added the fix for displaying id and value in search output action as datapill.
Released the latest version. This should be enabled for Non EU region.
@duncancasemore Please release for EU region.
