### ISSUE TITLE
Unable to start recipes with Applaud triggers after migration

### ISSUE THREAD

**Issue by kushalapplaud** [ApplaudSolutions/Applaud-Workato-Connector#44]
**Describe the bug**
Unable to start recipes with Applaud triggers after migration

**Steps to reproduce**
1. Using new/updated instance and workflow action
1. In workflow I have created a trigger integration
1. When this got migrated the recipe was live
1. Now in UAT when I am trying to start the recipe this gives error
1. See error

**Expected behavior**
This should work fine 

**Screenshots**
![image](https://user-images.githubusercontent.com/45057962/161913940-855f7578-4713-49e0-a4a9-b4cf04e068b4.png)

**URL**
https://uat-kch-nhs-uk.tryapplaud-eu.com/

**Additional context**
This works fine when I change the name of the trigger integration action in workflow and then in recipe I select the workflow action with new name. But i shouldn't have to do this after every mgiration.

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by vinaykumarkasireddy** [comment]
This is not issue with SDK. Need to stop the recipes before doing the migration. 
Stop all the recipes, create manifest, download the manifest, upload and install the manifest to the new tenant and then start the recipes.
If the issue still persists, please raise ticket with workato.
