### ISSUE TITLE
Retry the calls twice after first call if response is 502 error

### ISSUE THREAD

**Issue by kushalapplaud** [ApplaudSolutions/Applaud-Workato-Connector#46]
## Summary

1. **As a** configurator
1. **I want** the recipe actions to retry twice after first call if there is any 502 error

## Acceptance Criteria

1. After the first call actions should repeat twice if 502 error is in response for GET, CREATE, UPDATE ,DELETE except for Bulk Upsert.

### [Title of wireframe/mockup 1]
[Image of wireframe/mockup 1]

### [Title of wireframe/mockup 2]
[Image of wireframe/mockup 2]

## Notes

* > Here goes a quote from an email
* Here goes any other useful information…

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by ssarap** [comment]
@kushalapplaud Please find the connector shared via  https://app.workato.com/custom_adapters/33191/details?token=363f7bc0
This is changes for retry on Search. Please test it and see if the issue is resolved.

**Comment by kushalapplaud** [comment]
@ssarap Link is redirecting to stage tenant but not the sdk download option.

**Comment by duncancasemore** [comment]
@ssarap are you sure we should be doing this? Aren't we just masking underlying issues that will occur if a customer tries to integrate without Workato?

**Comment by hgajula-applaud** [comment]
This is an ER and has to be reviewed and approved by @ApplaudSolutions/product-management

**Comment by kushalapplaud** [comment]
@hgajula-applaud @duncancasemore - We have been facing 502 in recipes and these are intermittent. Capita team has asked for a reason for this because they have flagged it as Sev-2 and they want to understand the risk involved in PROD because of this issue. Dev team is unable to provide any numbers as such because there is no guarantee this happens only for high concurrency.

@satchava @karthmoh me and sumanth had a call to discuss the scenarios and possibilities and we came up with this solution. Our UI does the same in front end where they retry the call twice whenever there is any 502 error. So retrying the recipe action will also resolve this and the risk in prod reduces.

We can remove this as a UAT sign off blocker with this.

**Comment by ssarap** [comment]
@duncancasemore This wouldn't get into the SDK till Product management approves. 
Services team has been struggling with 502 error and they were checking if we can do a retry within Applaud Connector as the same thing is being done in UI. Considering this as a SPIKE story, tried to review the feasibility and can confirm that this is feasible.

**Comment by duncancasemore** [comment]
@ssarap great yes please see if feasible.

I've spoken to @lewie6 and am open to introducing this TEMPORARILY. I'd like us to plan to remove it later in the year though.

**Comment by kushalapplaud** [comment]
@ssarap - Can you please work on the PATCH and POST request as well. So that we can get that deployed in TA and test it for all cases.

**Comment by ssarap** [comment]
@vinaykumarkasireddy Could you pls pick this up.

**Comment by kushalapplaud** [comment]
@vinaykumarkasireddy @ssarap Do we have an update on this? Client has marked this as Sev-2 which is a go live blocker and they are asking for update on this everyday. Any ETA?

**Comment by ssarap** [comment]
@kushalapplaud We are on it.

**Comment by vinaykumarkasireddy** [comment]
@kushalapplaud Added retry calls for create/update/upsert/delete and search actions. Please test the changes using the below connector.
https://app.workato.com/custom_adapters/25457/details?token=56e5f206
Will release the code as soon as the testing is done.

**Comment by kushalapplaud** [comment]
@satchava can you please confirm once if we need this for upsert or will this cause issue for upsert.

**Comment by satchava** [comment]
@vinaykumarkasireddy we should not be doing this for bulkupsert.

**Comment by vinaykumarkasireddy** [comment]
@satchava @kushalapplaud Please let me know for which actions we need this. 
Removing for bulkUpsert.

At present, doing this for below actions.
Create
Update
Upsert
Delete
Search
BulkCreate
BulkDelete.

**Comment by kushalapplaud** [comment]
@vinaykumarkasireddy Apart from Upsert all are okay. @satchava Please confirm once.

**Comment by satchava** [comment]
@vinaykumarkasireddy we should remove all bulk actions here

**Comment by vinaykumarkasireddy** [comment]
Added retry calls for below actions.
Create, Update, Upsert, Delete and Search actions.
Released the latest version. This should be enabled for Non EU region.
@duncancasemore Please release for EU region.

**Comment by kushalapplaud** [comment]
@duncancasemore Please let us know once this is released for EU region.
