### ISSUE TITLE
New/updated instance real-time trigger

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#6]
## Summary

1. **As a** Integrations Designer
1. **I want** to create recipes that trigger in real-time from new or updated Applaud instances
1. **so that** I can integrate actions performed in Applaud with other applications

## Acceptance Criteria

1. I can select a 'New/updated instance' real-time trigger for the Applaud app
1. I see that this trigger is labeled Real-time
1. I can set the model, which has the same behavior as #5
1. I can see the generated webhook URL as per the wireframe
1. I do not see the When first started, trigger interval or batch size options for real-time triggers
1. I can set trigger conditions just as I can in #5
1. In subsequent actions in the recipe, I can see the model properties available as datapills.  I see that each Applaud property type is typed correctly in its datapill
1. When I save a real-time trigger, I see that this automatically creates a workflow in Applaud just the same as #5.  Except in this case the enrollment criteria for the workflow are both 'Create' and 'Update' actions
1. I see that newly created instances in Applaud trigger the recipe in real-time
1. I see that updated instances in Applaud trigger the recipe in real-time
1. If I update the real-time trigger, I see that this does not create a duplicate workflow in Applaud. Instead, I see it first checks that a workflow 'Fire Webhook' action does not already exist for the webhook URL before attempting to create one
1. I can modify the Applaud workflow to have other conditions or capabilities (eg, fire the webhook in an if condition, or delete the generated workflow and instead move the Fire Webhook action to the end of an existing approval workflow) and that a) it still triggers, and b) doesn't create duplicate workflows when editing the trigger

### New/updated real-time trigger

![Applaud trigger setup](https://user-images.githubusercontent.com/7467052/94832532-ecda2900-0405-11eb-8231-706941f4c777.png)

## Open Issues

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by vinaykumarkasireddy** [comment]
Dependent on the cloud git https://github.com/ApplaudSolutions/applaud-cloud/issues/3145

**Comment by vinaykumarkasireddy** [comment]
Verified the real time triggers on stage.
This is working fine.

Completion checklist:
1. [x] I can select 'New/updated instance' real time trigger.
1. [x] I see that this trigger is labeled real time.
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/80c6b9de-676a-4288-9d66-df4b55f64fdb)
1. [x] I can select the model.
1. [x] I can select the workflow action for which the webhook url to be updated.
1. [x] Webhook url is getting updated against the workflow action that is selected, when the recipe is started.
1. [x] I can see the status changed to 'live' when the recipe is active.
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/da986383-d500-4b4e-a2a2-2463f3d11562)
1. [x] Webhook url is updated to null when the recipe is stopped.
1. [x] I can see status changed to 'not live' when the recipe is not active.
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/cd0f9673-31cb-4f1d-aa13-fd93cfb57b94)
1. [x] In subsequent actions in the recipe, I can see the model properties available as datapills. I see that each Applaud property type is typed correctly in its datapill
![image.png](https://images.zenhubusercontent.com/57876b29e40e5714b16c1178/45ee1f27-c436-48f1-bba0-88b05227e68a)
