### ISSUE TITLE
Option to trigger a recipe from an existing Applaud workflow

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#9]
## Summary

1. **As a** Integration Designer
1. **I want** to trigger recipes from within an existing Applaud workflow
1. **so that** I can control when the trigger fires, such as at the end of an approval workflow

## Acceptance Criteria

1. I can select the triggering workflow action, which gives me a list of all workflows+integration actions linked to the selected model
1. I see the triggering workflow action is a required field
1. I see a list of all workflows for that model where the triggering event of the recipe matches the triggering event of the workflow.  For example, if a workflow is "create+update" but the recipe is "create" I wouldn't see it.  
1. I see both activated and deactivated workflows
1. I see the workflows + actions presented in alphabetical order
1. If I pick a workflow action that is used as a trigger for another recipe, I see the error: "This workflow action is already used by the recipe "{recipe name}"
1. When I save the trigger, this links the recipe to that Applaud workflow action so that other recipes can't use it.
1. When I save the trigger, I see that the status is 'Not live' in Applaud
1. When I activate the recipe, I note that this dynamically sets the webhook URL in the Applaud action.  I see that the status in Applaud changes to 'Live'.
1. When I deactivate the recipe, I note that this dynamically removes the webhook URL from the Applaud action.  I see that the status in Applaud changes to 'Not live'.

### Workflow settings for real-time triggers
<img width="1490" alt="Screenshot 2020-12-11 at 10 46 52" src="https://user-images.githubusercontent.com/7467052/101894556-3e3d2c00-3b9e-11eb-8063-7265cb0debba.png">

## Notes

* None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by vinaykumarkasireddy** [comment]
Closing this as this is not required any more.
